/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react';
import Head from 'next/head';
import Layout from '../components/layout/layout';
// import LandingBackground from '../components/LandingBackground';
// import LandingSkills from '../components/LandingSkills';
// import LandingExperiences from '../components/LandingExperiences';
import LandingIntro from '../components/LandingIntro';
import LandingSideSocialLinks from '../components/LandingSideSocialLinks';

const containerStyle = css`
  background-color: inherit;
  display: flex;
  flex-direction: column;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Sleeepy Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <LandingSideSocialLinks />
        <div css={containerStyle}>
          <LandingIntro />
        </div>
      </Layout>
    </>
  );
}
